name: YARA Rule Validation
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install YARA
        run: |
          sudo apt-get install yara
      - name: Syntax Check
        run: |
          find ./Yara -name "*.yar" -exec yara {} /dev/null \;

